name: Publish Sync Server Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/anki-sync-server

jobs:
  build-and-push:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Anki version
        id: version
        run: |
          set -euo pipefail
          VERSION=$(cat .version | tr -d '\n')
          if [[ -z "$VERSION" ]]; then
            echo "Detected empty version string" >&2
            exit 1
          fi
          echo "value=$VERSION" >>"$GITHUB_OUTPUT"

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.version.outputs.value }}
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=Anki Sync Server
            org.opencontainers.image.description=Self-hosted Anki sync server built from the Anki source tree
            org.opencontainers.image.version=${{ steps.version.outputs.value }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: docs/syncserver
          file: docs/syncserver/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ANKI_VERSION=${{ steps.version.outputs.value }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
